#include "hover_mfc.h"

IMPLEMENT_DYNAMIC(CGameObj, CObject);
IMPLEMENT_DYNAMIC(CPodObj, CGameObj);
IMPLEMENT_DYNAMIC(CFloorObj, CGameObj);
IMPLEMENT_DYNAMIC(CBeacon, CGameObj);
IMPLEMENT_DYNAMIC(CPlayer, CGameObj);
IMPLEMENT_DYNAMIC(CHumanPlayer, CPlayer);
IMPLEMENT_DYNAMIC(CRobotPlayer, CPlayer);
IMPLEMENT_DYNAMIC(CFlag, CPodObj);
IMPLEMENT_DYNAMIC(CContainer, CPodObj);
IMPLEMENT_DYNAMIC(CInviciblePod, CPodObj);
IMPLEMENT_DYNAMIC(CMapEraserPod, CPodObj);
IMPLEMENT_DYNAMIC(CJumpPod, CPodObj);
IMPLEMENT_DYNAMIC(CSlowPod, CPodObj);
IMPLEMENT_DYNAMIC(CFlagRemover, CFloorObj);
IMPLEMENT_DYNAMIC(CSledPad, CFloorObj);
IMPLEMENT_DYNAMIC(CHoldPad, CFloorObj);
IMPLEMENT_DYNAMIC(CWall, CGameObj);
IMPLEMENT_DYNCREATE(CBumperDoc, CDocument);
IMPLEMENT_DYNCREATE(CBumperView, CView);
IMPLEMENT_DYNAMIC(CCollider, CObject);
IMPLEMENT_DYNAMIC(CRegionMatrix, CObject);
IMPLEMENT_DYNAMIC(CSmokeBombPod, CPodObj);
IMPLEMENT_DYNAMIC(CSpeedPod, CPodObj);
IMPLEMENT_DYNAMIC(CTempWallPod, CPodObj);


// STUB: HOVER 0x40c480
void CBumperView::OnDraw(CDC*)
{
    // TODO
}
